/* ce8d61308991e60004ec2bd1e2d78c0c02c980b4
 * This file is automatically generated by graphql-let. */

import * as Types from '../../__types__';

import { useMutation, UseMutationOptions } from 'react-query';

function fetcher<TData, TVariables>(endpoint: string, requestInit: RequestInit, query: string, variables?: TVariables) {
  return async (): Promise<TData> => {
    const res = await fetch(endpoint, {
      method: 'POST',
      ...requestInit,
      body: JSON.stringify({ query, variables }),
    });

    const json = await res.json();

    if (json.errors) {
      const { message } = json.errors[0];

      throw new Error(message);
    }

    return json.data;
  }
}
export type CreateLinkMutationVariables = Types.Exact<{
  title: Types.Scalars['String'];
  url: Types.Scalars['String'];
  imageUrl: Types.Scalars['String'];
  category: Types.Scalars['String'];
  description: Types.Scalars['String'];
}>;


export type CreateLinkMutation = { __typename?: 'Mutation', createLink?: { __typename?: 'Link', title?: string | null, url?: string | null, imageUrl?: string | null, category?: string | null, description?: string | null } | null };


export const CreateLinkDocument = `
    mutation CreateLink($title: String!, $url: String!, $imageUrl: String!, $category: String!, $description: String!) {
  createLink(
    title: $title
    url: $url
    imageUrl: $imageUrl
    category: $category
    description: $description
  ) {
    title
    url
    imageUrl
    category
    description
  }
}
    `;
export const useCreateLinkMutation = <
      TError = unknown,
      TContext = unknown
    >(
      dataSource: { endpoint: string, fetchParams?: RequestInit },
      options?: UseMutationOptions<CreateLinkMutation, TError, CreateLinkMutationVariables, TContext>
    ) =>
    useMutation<CreateLinkMutation, TError, CreateLinkMutationVariables, TContext>(
      ['CreateLink'],
      (variables?: CreateLinkMutationVariables) => fetcher<CreateLinkMutation, CreateLinkMutationVariables>(dataSource.endpoint, dataSource.fetchParams || {}, CreateLinkDocument, variables)(),
      options
    );